In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4],[7,6,8,9]])
print(a)

[[1 2 3 4]
 [7 6 8 9]]


In [3]:
print(np.min(a))

1


In [4]:
print(np.min(a,axis=0)) #specify axis for the direction in case of multidimension array

[1 2 3 4]


In [5]:
print(np.min(a,axis=1))

[1 6]


In [6]:
#mean average all the elements

In [7]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)

3.0


In [8]:
print(np.mean(b))

3.0


In [9]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[4.  4.  5.5 6.5]
[2.5 7.5]


In [10]:
#median of the elements 

In [11]:
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [12]:
#mean vs average
print(np.mean(c))

2.4


In [13]:
w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.066666666666667


In [15]:
#standard deviation
u=np.mean(c)
myStd= np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [16]:
# inbuilt function
dev = np.std(c)
print(dev)

1.854723699099141


In [18]:
#variance 

print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
