In [4]:
import numpy as np

In [5]:
# numpy random module
#rand:  random values in a given shape 
#randint: return random ingers from low (inclusive) to high (Exclusive)
#random: return random floats in the half-open interval[0.0,1.0]
#choice: generates a random sample from a given 1-D array 
#shuffle : shuffles the content of a squence

In [7]:
a = np.arange(10) 
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[8 6]


In [13]:
#returns values from a standard normal distribution
a= np.random.rand(2,3)
print(a)

a=np.random.randint(5,10,2)
print(a)

#randomly pick one element from an array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[[0.59433721 0.58853185 0.02487911]
 [0.93395405 0.49209719 0.38132001]]
[8 6]
3
