In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [5]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [10]:
#create array of zeroes , ones,custom array
a=np.zeros((3,3))
print(a)

randomMatrix= np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.2069104  0.82454364 0.63807207]
 [0.16617395 0.45683826 0.34109004]]


In [12]:
print(randomMatrix[:, 1])

[0.82454364 0.45683826]


In [13]:
randomMatrix[1,1:] = 1 #slicing
print(randomMatrix)

[[0.2069104  0.82454364 0.63807207]
 [0.16617395 1.         1.        ]]


In [18]:
#set some rows and columns with any values
z = np.zeros((3,3), dtype=np.int64)
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [19]:
#data types
print(z.dtype)

int64


In [20]:
#Mathematicla operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)

print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [21]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))






[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [22]:
#matrix multiplication / dot product

In [23]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [24]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [25]:
#multiplication of vectors

In [26]:
a=np.array([1,2,3,4])
b=np.array([12,13,16,17])
print(a.dot(b))

154


In [27]:
print(a)

[1 2 3 4]


In [28]:
print(sum(a))

10


In [29]:
print(x)

[[1 2]
 [3 4]]


In [31]:
print(np.sum(x))
print(np.sum(x,axis=0))

10
[4 6]


In [32]:
#stacking of arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[144 169 256 289]


In [36]:
a=np.stack((a,b),axis=0)

In [35]:
#reshape a numpy array


In [37]:
print(a)

[[  1   2   3   4]
 [144 169 256 289]]


In [43]:
a=a.reshape((-1,4))
print(a)

[[  1   2   3   4]
 [144 169 256 289]]
